openweather:
  api:
    key: ee6bbf09dcc0ab10e314eda8dce3dc74
app:
  url:
    base: http://api.openweathermap.org/data/2.5/weather
  mongo:
    name: weatherClient
    url: mongodb://localhost:27017/
#spring:
#  data:
#    mongodb:
#      uuid-representation:
